name: LokiQuests
main: net.nimbus.lokiquests.LQuests
version: 1.0
softdepend: [HolographicDisplays, NimbusAPI]
api-version: 1.20
commands:
  lquest:
  quest:
    aliases: [q]
  dungeon:
    aliases: [dun]
  party:
  leave:
  setspawnplace: